name: fraud-detection-analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2
  - numpy=1.26
  - scikit-learn=1.4
  - xgboost=2.0
  - imbalanced-learn=0.12
  - matplotlib=3.8
  - seaborn=0.13
  - jupyter=1.0
  - jupyterlab=4.1
  - pip
  - pip:
      - shap==0.45.0
      - fairlearn==0.10.0
      - mlflow==2.11.0
      - dvc==3.48.0
      - dvc-s3==3.1.0
      - great-expectations==0.18.10
      - python-dotenv==1.0.1
